name: Create Issue in Jira

on:
  issues:
    types:
      - opened

jobs:
  create_jira_issue:
    uses: XeroAPI/Xero-OpenAPI/.github/workflows/jira_create_issue.yml@fd9d44b04bf4934a7509b8e7ece51a9e0e462e4f # master
    secrets: inherit
